### ISSUE TITLE
Crashed when loading

### ISSUE THREAD

**Issue by vizthex123** [Nyfaria/DynamicSurroundingsResurrected#3]
Not sure what happened, but disabling the mod fixed it.

Log:
[latest.log](https://github.com/Nyfaria/DynamicSurroundingsResurrected/files/8885039/latest.log)

**Comment by Nyfaria** [comment]
this log has nothing to do with DynamicSurroundingsResurrected

**Comment by vizthex123** [comment]
Odd, cuz the game loaded fine when I disabled the mod.

**Comment by Nyfaria** [comment]
well the log says solar cooking is missing a dependency, nothing else. provide a crash log instead

**Comment by Nyfaria** [comment]
need a crash log though, your latest log doesnt say anything

**Comment by Zynthwave** [comment]
So maybe this will help, Im crashing when loading the game and It gives this popup:

The game crashed whilst rendering overlay
Error: java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.sndctrl.audio.SoundUtils
Exit Code: -1

I'm not sure the best way to give the crash log other than copy/pasting it so Ill try to do that here...

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 6/22/22, 12:21 PM
Description: Rendering overlay

java.lang.NoClassDefFoundError: Could not initialize class org.orecruncher.sndctrl.audio.SoundUtils
	at net.minecraft.client.sounds.SoundEngine.handler$zzf000$initialize(SoundEngine.java:656) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sndctrl.json:MixinSoundEngine,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundEngine.m_120323_(SoundEngine.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sndctrl.json:MixinSoundEngine,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundEngine.m_120239_(SoundEngine.java:94) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sndctrl.json:MixinSoundEngine,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundManager.m_5787_(SoundManager.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at net.minecraft.client.sounds.SoundManager.m_5787_(SoundManager.java:39) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:212) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:199) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:442) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1066) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.sounds.SoundEngine.handler$zzf000$initialize(SoundEngine.java:656) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sndctrl.json:MixinSoundEngine,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundEngine.m_120323_(SoundEngine.java:101) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sndctrl.json:MixinSoundEngine,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundEngine.m_120239_(SoundEngine.java:94) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sndctrl.json:MixinSoundEngine,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundManager.m_5787_(SoundManager.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at net.minecraft.client.sounds.SoundManager.m_5787_(SoundManager.java:39) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:212) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:OptiFine:default}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:199) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,xf:OptiFine:default}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1261) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2316!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: Default, FallPack_1.18_v1.4.zip
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.IllegalAccessError: class org.orecruncher.sndctrl.audio.SoundUtils tried to access private field net.minecraft.client.sounds.SoundManager.f_120349_ (org.orecruncher.sndctrl.audio.SoundUtils is in module dsurround@5.0.0.0 of loader 'TRANSFORMER' @6c6017b9; net.minecraft.client.sounds.SoundManager is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6c6017b9)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:68)
	at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:212)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:199)
	at TRANSFORMER/minecraft@1.18.2/com.mojang.blaze3d.platform.Window.m_85435_(Window.java:442)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1066)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.IllegalAccessError: class org.orecruncher.sndctrl.audio.SoundUtils tried to access private field net.minecraft.client.sounds.SoundManager.f_120349_ (org.orecruncher.sndctrl.audio.SoundUtils is in module dsurround@5.0.0.0 of loader 'TRANSFORMER' @6c6017b9; net.minecraft.client.sounds.SoundManager is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6c6017b9)
	at TRANSFORMER/dsurround@5.0.0.0/org.orecruncher.sndctrl.audio.SoundUtils.<clinit>(SoundUtils.java:77)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundEngine.handler$zzf000$initialize(SoundEngine.java:656)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundEngine.m_120323_(SoundEngine.java:101)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundEngine.m_120239_(SoundEngine.java:94)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundManager.m_5787_(SoundManager.java:116)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.sounds.SoundManager.m_5787_(SoundManager.java:39)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
	... 29 more


-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1399272704 bytes (1334 MiB) / 1879048192 bytes (1792 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 2080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e07
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1215
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 49060.45
	Virtual memory used (MB): 25437.77
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 492.67
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.2-forge-40.1.0
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.15, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 3900X 12-Core Processor 
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.1.02.1.zip
	OpenGlVersion: 3.2.0 NVIDIA 512.15
	OpenGlRenderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 24
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.18.2-40.1.0-universal.jar                 |Forge                         |forge                         |40.1.0              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
